module.exports = {
  CHANGE_STATUS_SUCCESS: "Cập nhật status thành công",
  CHANGE_STATUS_MULTI_SUCCESS: "Có %d phần tử được cập nhật status thành công",
  CHANGE_ORDERING_SUCCESS: "Cập nhật ordering thành công",
  DELETE_SUCCESS: "Xóa phần tử thành công",
  DELETE_MULTI_SUCCESS: "Có %d phần tử được xóa thành công",
  ADD_SUCCESS: "Thêm mới phần tử thành công",
  EDIT_SUCCESS: "Cập nhật thông tin phần tử thành công",
  ERROR_NAME: "Chiều dài name từ %d đến %d ký tự",
  ERROR_ORDERING: "Phải là số nguyên lớn hơn %d và bé hơn %d",
  ERROR_STATUS: "Phải là một giá trị khác rỗng",
  ERROR_CONTENT: "Chiều dài content từ %d đến %d ký tự",
  ERROR_LOGIN_USERNAME_NOTEXIST: "Username không tồn tại",
  ERROR_LOGIN_PASSWORD_INCORRECT: "Password không chính xác",
  SUCCESS_SIGNUP: "Đăng ký tài khoản thành công",
  SUCCESS_INVOICE: "Đặt hàng thành công",
  ERROR_CHECK_CODE: "Mã kích hoạt không đúng",
};
